import json
import re
import argparse
import os

def assign_tags(title, content):
    text = (title + " " + content).lower()
    tags = []
    if any(w in text for w in ['railway', 'refraction', 'station']):
        tags.append("Refraction Railway")
    if any(w in text for w in ['walpurgis']):
        tags.append("Walpurgis Night")
    if any(w in text for w in ['mirror dungeon', 'mirror of the']):
        tags.append("Mirror Dungeon")
    if any(w in text for w in ['update', 'maintenance', 'scheduled', 'hotfix']):
        tags.append("Update")
    if any(w in text for w in ['issue', 'fixed', 'error', 'bug', 'known issues']):
        tags.append("Bug Fix")
    if any(w in text for w in ['compensation', 'apologize', 'apology']):
        tags.append("Notice")
    if not tags:
        tags.append("Announcement")
    return tags[:3]

def convert_txt_to_json(input_txt, input_dates, output_file):
    dates_map = {}
    try:
        with open(input_dates, "r", encoding="utf-8") as f:
            for line in f:
                parts = line.strip().split('\t')
                if len(parts) == 2:
                    dates_map[int(parts[0])] = parts[1]
    except FileNotFoundError:
        print(f"Warning: Sidecar dates file '{input_dates}' not found. Notices will have empty dates.")

    with open(input_txt, "r", encoding="utf-8") as f:
        text = f.read()

    notices = []
    pattern = re.compile(
        r"Writing Sample\s+(\d+):\s*\n([\s\S]*?)(?=\nWriting Sample\s+\d+:\s*\n|\Z)",
        re.MULTILINE
    )

    for match in pattern.finditer(text):
        notice_id = int(match.group(1))
        full_block = match.group(2).strip()

        if full_block.startswith("‘") and full_block.endswith("’"):
            full_block = full_block[1:-1].strip()
        elif full_block.startswith("'") and full_block.endswith("'"):
            full_block = full_block[1:-1].strip()
        elif full_block.startswith('"') and full_block.endswith('"'):
            full_block = full_block[1:-1].strip()

        lines = full_block.splitlines()
        while lines and not lines[0].strip():
            lines.pop(0)

        if not lines:
            continue

        title = lines[0].strip()
        content_body = "\n".join(lines[1:]).strip()
        tags = assign_tags(title, content_body)
        
        date_str = dates_map.get(notice_id, "")

        notices.append({
            "id": notice_id,
            "title": title,
            "date": date_str,
            "tags": tags,
            "content": content_body
        })

    with open(output_file, "w", encoding="utf-8") as f:
        json.dump(notices, f, indent=2, ensure_ascii=False)

    print(f"✅ Successfully converted {len(notices)} notices to '{output_file}'")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Convert Limbus Company TXT to structured JSON using Sidecar dates.")
    parser.add_argument("input_txt", help="Input TXT file")
    parser.add_argument("input_dates", help="Input TSV dates file generated by C")
    parser.add_argument("output", help="Output JSON file")
    args = parser.parse_args()
    
    convert_txt_to_json(args.input_txt, args.input_dates, args.output)